c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2019                     # [win]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2019                     # [win]
numpy:
  - 1.23
python:
  - 3.9
channels:
  - local
  - dbanas
  - conda-forge
  - defaults
  - labscript-suite
