{% set name = "chaco" %}
{% set version = "5.1.1" %}
{% set enable_version = "5.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/enthought/chaco.git
  git_rev: {{ version }}

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  script_env:
    - ETS_QT4_IMPORTS=1

requirements:
  build:
    - {{ compiler('c')   }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libglu-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('mesa-dri1-drivers') }}     # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - cmake
    - git
    - swig
  host:
    - Cython
    - enable ={{ enable_version }}
    - importlib_resources
    - numpy {{ numpy }}
    - pyface >=7.4.2
    - python {{ python }}
    - setuptools
  run:
    - enable ={{ enable_version }}
    - importlib_resources
    - {{ pin_compatible('numpy') }}
    - pyface >=7.4.2
    - python

test:
  # Python imports
  imports:
    - chaco
    - chaco.api
    - chaco.ui

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://docs.enthought.com/chaco
  license: BSD License
  summary: 'interactive 2-dimensional plotting'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

extra:
  recipe-maintainers:
    - capn-freako
