{% set name = "chaco" %}
{% set version = "5.0.0.2" %}
{% set enable_version = "5.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/enthought/chaco.git
  git_rev: 5.0.0
build:
  number: 6
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - setuptools
    - vs2019_win-64        # Uncomment for Windows build only.
    # - {{compiler('c')}}    # Would like to get one of these working, instead of above hack.
    # - {{compiler('cxx')}}
    - git
    - cmake

  host:
    - python
    - enable ={{enable_version}}
    - Cython
    - importlib_resources
    - pyface >=7.4.2

  run:
    - enable ={{enable_version}}
    - importlib_resources
    - pyface >=7.4.2

test:
  # Python imports
  imports:
    - chaco
    - chaco.api
    # - chaco.contour
    # - chaco.downsample
    # - chaco.downsample.tests
    # - chaco.layers
    # - chaco.overlays
    # - chaco.plugin
    # - chaco.scales
    # - chaco.scales.tests
    # - chaco.shell
    # - chaco.tests
    # - chaco.tools
    # - chaco.tools.tests
    # - chaco.tools.toolbars
    - chaco.ui

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://docs.enthought.com/chaco
  license: BSD License
  summary: 'interactive 2-dimensional plotting'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

extra:
  recipe-maintainers:
    - capn-freako
