from _typeshed import Incomplete
from collections.abc import Generator
from pyibisami.ami.model import AMIModel as AMIModel
from pyibisami.common import TestSweep as TestSweep

def plot_name(tst_name, n: int = 0) -> Generator[Incomplete]: ...
def hsv2rgb(hue: int = 0, saturation: float = 1.0, value: float = 1.0): ...
def color_picker(num_hues: int = 3, first_hue: int = 0) -> Generator[Incomplete]: ...
def expand_params(input_parameters: str) -> list[TestSweep]: ...
def run_tests(**kwargs) -> None: ...
def main(**kwargs) -> None: ...
