from _typeshed import Incomplete
from collections.abc import Generator
from pyibisami.ami.model import AMIModel as AMIModel

def plot_name(tst_name, n: int = ...) -> Generator[Incomplete, None, None]: ...
def hsv2rgb(hue: int = ..., saturation: float = ..., value: float = ...): ...
def color_picker(num_hues: int = ..., first_hue: int = ...) -> Generator[Incomplete, None, None]: ...
def expand_params(input_parameters): ...
def run_tests(**kwargs) -> None: ...
def main(**kwargs) -> None: ...
