from _typeshed import Incomplete
from typing import Any

ParamDict: Incomplete
NamedParamDict: Incomplete
TestDefinition: Incomplete
param_types: Incomplete

def print_param(indent, name, param) -> None: ...
def print_code(pname, param) -> None: ...
def mk_model(ibis_params: ParamDict, ami_params: ParamDict, model_name: str, description: str, out_dir: str = '.') -> None: ...
def ami_config(py_file) -> None: ...
def mk_combs(dict_items: list[tuple[str, Any]]) -> list[list[tuple[str, Any]]]: ...
def mk_tests(test_defs: dict[str, TestDefinition], file_base_name: str, test_dir: str = 'test_runs') -> None: ...
def main(py_file) -> None: ...
