from _typeshed import Incomplete

param_types: Incomplete

def print_param(indent, name, param) -> None: ...
def print_code(pname, param) -> None: ...
def mk_model(ibis_params, ami_params, model_name, description, out_dir: str = ...) -> None: ...
def ami_config(py_file) -> None: ...
def mk_combs(dict_items): ...
def mk_tests(test_defs, file_base_name, test_dir: str = ...) -> None: ...
def main(py_file, **kwd_args) -> None: ...
