{% set name = "enable" %}
{% set version = "6.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/enthought/{{name}}.git
  git_rev: {{version}}

build:
  number: 1
  script: " {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  script_env:
    - CFLAGS=-Wno-c++11-narrowing -Wno-register -Wno-incompatible-function-pointer-types

requirements:
  build:
    - {{ compiler('c')   }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libglu-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('mesa-dri1-drivers') }}     # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - cmake
    - Cython <3
    - git
    - pip <23
    - python {{ python }}
    - swig
  host:
    - Cython <3
    - fonttools
    - numpy {{ numpy }}
    - pillow >=10.1
    - pip <23
    - pyface >=8
    - pyparsing
    - pyside6 >=6.6.1
    - python {{ python }}
    - setuptools
    - traitsui >=8
    - xorg-libxfixes                     # [linux]
  run:
    - fonttools
    - {{ pin_compatible('numpy') }}
    - pillow >=10.1
    - pyface >=8
    - pyparsing
    - pyside6 >=6.6.1
    - python
    - traitsui >=8

test:
  imports:
    - enable
    - enable.drawing
    - enable.gadgets
    - enable.layout
    - enable.null
    - enable.primitives
    - enable.qt
    - enable.savage
    - enable.savage.compliance
    - enable.savage.svg
    - enable.savage.svg.backends
    - enable.savage.svg.backends.kiva
    - enable.savage.svg.backends.null
    - enable.savage.svg.backends.wx
    - enable.savage.svg.css
    - enable.savage.svg.tests
    - enable.savage.svg.tests.css
    - enable.savage.trait_defs
    - enable.savage.trait_defs.ui
    - enable.savage.trait_defs.ui.qt
    - enable.savage.trait_defs.ui.wx
    - enable.tests
    - enable.tests.primitives
    - enable.tests.qt
    - enable.tests.tools
    - enable.tests.wx
    - enable.tools
    - enable.tools.apptools
    - enable.tools.pyface
    - enable.tools.toolbars
    - enable.trait_defs
    - enable.trait_defs.ui
    - enable.trait_defs.ui.qt
    - enable.trait_defs.ui.wx
    - enable.wx
    - kiva
    - kiva.agg
    - kiva.agg.tests
    - kiva.fonttools
    - kiva.fonttools.tests
    - kiva.quartz
    - kiva.tests
    - kiva.tests.agg
    - kiva.trait_defs
    - kiva.trait_defs.ui
    - kiva.trait_defs.ui.wx

about:
  home: "https://github.com/enthought/enable/"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "low-level drawing and interaction"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - capn-freako
