{% set name = "parsec" %}
{% set version = "3.5" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../../parsec.py

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - parsec

about:
  home: https://github.com/sighingnow/parsec.py
  license: MIT License
  summary: 'parser combinator.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
